_format_version: "3.0"

services:
  # 认证服务
  - name: auth-service
    url: http://auth-service:8080
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  # 数据服务
  - name: data-service
    url: http://data-service:8080
    routes:
      - name: data-route
        paths:
          - /api/data
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  # 健康检查
  - name: health-check
    url: http://kong:8001/status
    routes:
      - name: health-route
        paths:
          - /health
        methods:
          - GET

plugins:
  # 限流插件
  - name: rate-limiting
    config:
      minute: 100
      hour: 10000
      policy: local

  # CORS插件
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  # 日志插件
  - name: file-log
    config:
      path: /tmp/kong.log
      reopen: true