global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

scrape_configs:
  # Prometheus 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (系统指标)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MVP Platform Services
  - job_name: 'mvp-auth-service'
    static_configs:
      - targets: ['auth-service:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # MVP Platform Local Demo
  - job_name: 'mvp-platform-local'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /api/metrics
    scrape_interval: 10s